version: '3'

services:
  flask:
    container_name: flask
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./src:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: server
    command: flask run --debugger --reload --host 0.0.0.0 --port 5000
